### ISSUE TITLE
Undefined property: stdClass::$enable_categories

### ISSUE THREAD

**Issue by itmagpro** [FictionLabs/FL-Yandex-Turbo#1]
Здравствуйте!

При открытии ссылки:
`https://example.com/?option=com_ajax&plugin=flyandexturbo&format=raw&code=xxxxxxxxxxxx&mode=categories`
в лог РНР гадит сообщением:
`PHP Notice:  Undefined property: stdClass::$enable_categories in /var/www/plugins/ajax/flyandexturbo/flyandexturbo.php on line 120`
Версия плагина: 3.2.0
Версия РНР: 7.2.32

Не критично, но лог РНР засерает.

**Comment by fiction13** [comment]
Добрый день.

Посмотрел. В теории такое может быть, когда плагин обновлен (появилась опция добавления категория), но не был пересохранен после этого (то есть опция не записалась в конфиг). Пробовали плагин пересохранить?

**Comment by itmagpro** [comment]
Здравствуйте!

Да, есть такое, забыл об этом глобальном "баге" - пересохранение настроек плагина помогло. Кстати, "Добрый день" давно штука не актуальная, а вот "Здравствуйте" во все времена в дефиците!:)

БлагоДарю!
